DEBUG = True
TESTING = True
SQLALCHEMY_DATABASE_URI = 'mysql://root:whatup@localhost/tests'
ATTACHMENTS_DIR = 'attachments'
MAX_CONTENT_LENGTH = 100 * 1024 * 1024  # 100 mb
SECRET_KEY = 'DEV KEY'
MIN_PASSWORD_LENGTH = 8
SUBS_PAGE_LENGTH = 20
